### ISSUE TITLE
allow disable compiler on preference page

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#104]
For larger workspaces it may make sense to disable build triggered (time consuming) compilation via compiler preference page. Also when working on a single project, you may save a file more often than you want to actually compile. Compilation would be activated by default, so this change has no negative impact. 

You already have implemented actions for compiling the edited and the viewed score which the user may invoke at the appropriate time.

**Comment by thSoft** [comment]
Automatic build can be already disabled quickly as an Eclipse workspace setting (in the Project menu), I think this is enough.

**Comment by nittka** [comment]
If I am not mistaken, this will also disable the Xtext builder, so linking etc. will be affected as well. What I'd want is a working Xtext tooling without "10 minute lilypond compiles" (which I have to cancel manually) on every save.

**Comment by thSoft** [comment]
Yes, you're right, this is a useful use case!
