### ISSUE TITLE
add "Show in" for compiled files

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#121]
If the score/audio view is closed, it is always quite cumbersome to view a file (Open the view, enable link with editor, select the file, disable link with editor).

I think, a context menu entries "Score View", "Audio View" would be great for pdf, midi and LilyPond files. Even with an open score view, using them would be nicer for the user as you do not have to use the "link with editor" button to open the file, but prevent the score view to try opening scores for uncomiled ily files...

**Comment by nittka** [comment]
needs both pull requests (elysium and commons)

**Comment by nittka** [comment]
If you want all (rather than only audio and score) views in the ScoreLibrary Show In context menu, use the following class definition rather than the individual commands;

`<dynamic
          class="org.eclipse.ui.ExtensionFactory:showInContribution"
          id="org.eclipse.ui.menus.dynamicShowInMenu">
        </dynamic>`

**Comment by thSoft** [comment]
This is a badly needed feature, thanks!

**Comment by nittka** [comment]
This feature has been introduced with Pull request #119.
