### ISSUE TITLE
Exception when include uri points to directory

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#125]
`\include ".."` causes an exception.
Should we just suppress directories and accept any file (file extension does not matter) or just known extensions.

**Comment by thSoft** [comment]
Good catch! There should be a validation rule that gives errors for including directories.

**Comment by nittka** [comment]
When creating the scope, only known file extensions are considered. Even if the LilyPond compiler works when including arbitrary text files with the correct content, we cannot register our parser for any file extension.

If the file extension is unknown a warning appears, informing the user about potential linking errors.
