### ISSUE TITLE
update syntax does not work on Windows

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#128]
The update syntax compiler preference does not work on Windows. I guess this is because the file used is a python script and not immediately executable.

**Comment by nittka** [comment]
I have tried to modify the command such that convert-ly is invoked. I get the output 

convert-ly.py (GNU LilyPond) 2.18.2

convert-ly.py: Processing `score.ly'... 
Applying conversion: 

and a score.ly~ file is created. However, it is identical to the original file. The missing verion is not added. What is the syntax updater supposed to do?

**Comment by nittka** [comment]
Another question concerning the current implementation. CompilerJob#updateSyntax always adds the --edit option and a potentially open file is closed (and then reopened). So isn't adding that option in SyntaxUpdaterProcessBuilderFactory redundant?

**Comment by thSoft** [comment]
Thank you, the `--edit` option was indeed added twice. I removed it as well as the commented out code.
