### ISSUE TITLE
Oomph setup fails

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#130]
With the current setup file, a clean installation fails. The problem is a missing version restriction for org.eclipse.emf.mwe2.launcher.feature.group. The xtext.sdk is restricted to before 2.8, but the resulting dependency installs an incompatible 2.9 launcher.

**Comment by thSoft** [comment]
I tried to fix this, it works for me now, please confirm it.

**Comment by nittka** [comment]
This is the modification, I did locally as well.
