### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by thSoft** [thSoft/elysium#141]
Prerequisite: the include files in the LilyPond installation should be copied to the build server.

**Comment by nittka** [comment]
I saw that the tests are failing. The lilypond path variable set for test execution looks as expected to me. Is there a way to check whether the shared files are present in the expected location (maybe add ls on the expected paths to the build script)?

**Comment by thSoft** [comment]
Yes, I experimented with Travis. Unfortunately `-Dlilypond.path=/home/travis/bin/lilypond` gets passed to Maven (see [build](https://travis-ci.org/thSoft/elysium/builds/345484398)), which is incorrect since it is only a symlink to the LilyPond executable in the real installation location. `build.sh` tries to resolve the symlink with `-Dlilypond.path=$(readlink -f "$(which lilypond)")` but somehow it doesn't resolve.

**Comment by thSoft** [comment]
Finally, the build is fixed: https://travis-ci.org/thSoft/elysium/

**Comment by nittka** [comment]
Congratulations!
