### ISSUE TITLE
use new pdf annotation structure

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#162]
With the next commons version, PdfAnnotation will have a uri field which should be used instead of the IFile field (LilyPondHyperlinkHelper). While commons is not released, the change cannot be made (maven relies on getting commons from the update site). 

@thSoft: How do you plan the next releases? Releasing both at the same time or releasing commons first, so that last minute changes could be made to Elysium. I would favour the second option.

**Comment by thSoft** [comment]
I'm willing to release Eclipse Commons 0.5 now and Elysium 0.6 later. Please confirm that Eclipse Commons can be really released and I'm going to do it.

**Comment by nittka** [comment]
I'm not quite sure yet of the state of the open PR in commons. On one hand, a central place for URI transformations is needed, on the other I don't have a good feeling about the API, yet.

Maybe, the best option is to start off with a Elysium version of the helper class, develop the API needed and move it to commons later. Also, maybe you could have a go at https://github.com/thSoft/eclipse-commons/issues/12 ;-) It bothers me and all my attempts at changing the control's width have been fruitless. Otherwise, I don't see any urgent issues that need fixing before a release.

Before releasing Elysium, I'd like the compiler, marker, syntax update and refactoring issues to be addressed. They should be part of the include resolution refactoring round.

**Comment by thSoft** [comment]
I released Eclipse Commons 0.5, you can proceed with this issue.
