### ISSUE TITLE
how to you run elysium core as a server node

### ISSUE THREAD

**Issue by arnoldvilleneuve** [thSoft/elysium#172]
how to you run elysium core as a server node

**Comment by nittka** [comment]
Could you elaborate on the use case, you have in mind? Elysium is (only) an IDE for LilyPond, i.e. it only provides an infrastructure for editing LilyPond files with navigation, invoking the LilyPond compiler, viewing compiled pdf files etc.

Core alone gives you no functionality beyond what compiling a file directly with LilyPond has. Unlike a "normal" Xtext project, Elysium does not have its own generator (producing some output from the model file which could be invoked without the IDE). It simply calls the LilyPond compiler via command line.

If you are asking which command line options Elysium uses to call LilyPond, see https://github.com/thSoft/elysium/blob/master/org.elysium.parent/org.elysium.ui/src/org/elysium/ui/compiler/CompilerProcessBuilderFactory.java. That is where the call is put together. At the moment the complete command is not shown in the console output, maybe this would be a good idea.

**Comment by thSoft** [comment]
@arnoldvilleneuve I don't quite understand your question. If it is about running Elysium in the browser: it is unfortunately out of the scope of this project. While it is theoretically possible with newer versions of Xtext, the issues mentioned by @nittka remain. For web-based LilyPond IDEs, check out http://lilybin.com or http://www.weblily.net.
