### ISSUE TITLE
add further refactoring preferences

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#186]
In PR #174 the following additions to the refactoring preference page were suggested:
* for disabling Refactoring participant completely (default refactoring enabled)
* for disabling "delete included file" warning (default warning enabled)
* for disabling deleting compiled files when deleting a source (default deleting compiled enabled)
* for disabling automatic include modification (default include modification enabled)

The first three were not controversial. The last one seems strange, as a primary goal of the refactoring participant is adapting the includes. Basically, this preference can be seen as a safety switch. While not disabling the refactoring help completely (e.g. movin compiled files as well), it allows disabling the include modifications in case of implementation errors lead to the destruction of includes when executing refactorings.

**Comment by nittka** [comment]
I would like to address this after #185 is reviewed (not necessarily merged) in order to prevent merge conflicts in the refactoring code.

**Comment by nittka** [comment]
I could not wait ;-) Based on the copileDirty branch, I added the preferences. I still think, adding the 4th more controversial preference does not hurt.

**Comment by nittka** [comment]
Resolved by merge of pull request.
This was the last open issue assigned to the next milestone. I do not plan to address further issues in the near future. So, what are your release plans?

**Comment by thSoft** [comment]
Great! I think it's time for a release. I'm going to do it today.
