### ISSUE TITLE
Score display broke after eclipse up

### ISSUE THREAD

**Issue by dickvalentine** [thSoft/elysium#196]
After recent update to Big Sur (Mac OS X 11), Elysium's Score display stopped working correctly. Content of the score pdf file is displayed as if the raster scan is offset, with what should be the upper left corner located in the lower mid-screen. The pdf file itself is correct, and displays correctly viewed with Apple Preview or pdf4Eclipse inside eclipse. Any advice about stopgaps I might try would be appreciated.

thanks,
--dick v

**Comment by thSoft** [comment]
I just updated my environment and managed to reproduce the issue, so I'm going to investigate it. Thanks for testing with macOS 11 and for your patience!

**Comment by dickvalentine** [comment]
Thank you so much for looking into the issue. I hope it turns out easy to rectify!! It would be a sad thing if Elysium were to become "abandon-ware." I've been using your plugin for a long time here, going back to at least 2008 or 09. For now, I'm going to be using an Eclipse perspective with pdf4eclipse in the elysium frame. It's not ideal, but seems to be the best workaround so far. Please feel free to contact me if you want me to test a new release in my environment.

**Comment by thSoft** [comment]
See https://github.com/thSoft/eclipse-commons/issues/59.

**Comment by dickvalentine** [comment]
thank you so much for looking into this matter. I attempted to view the
"invitation" you sent for collaboration on github, but github turns up a
404, page not found, for the link you provided.

In the past, I've install elysium by using the eclipse Marketplace. I
attempted to check for updates from eclipse, but it did not find your
updated code. What's the process for getting the improved score display
installed on my configuration?

thanks again!
--dick v

**Comment by dickvalentine** [comment]
Dear Mr Harmath,

I reviewed the comments you directed me to on the github website. remarks
claim that the pdf display anomaly I reported has been fixed and the issue
"closed." However, I have not been able to get the fixed display to work in
my environment. Updating eclipse to its 2021-03 version did not help. Do I
need to uninstall/reinstall elysium? If so, what are the steps?

Please let me know how to make elysium behave correctly in my environment.

thank you,
--dick valentine

**Comment by nittka** [comment]
There is no release of Elysium, yet. I hope, the new feature for the Audio-View will be reviewed and cleaned up soon, so that a new release can be built.

**Comment by thSoft** [comment]
I’ll review the outstanding PR today and prepare a new release this week.


2021. márc. 22. dátummal, 23:20 időpontban dickvalentine ***@***.***> írta:


Dear Mr Harmath,

I reviewed the comments you directed me to on the github website. remarks
claim that the pdf display anomaly I reported has been fixed and the issue
"closed." However, I have not been able to get the fixed display to work in
my environment. Updating eclipse to its 2021-03 version did not help. Do I
need to uninstall/reinstall elysium? If so, what are the steps?

Please let me know how to make elysium behave correctly in my environment.

thank you,
--dick valentine
