### ISSUE TITLE
Elysium removed from Eclipse Marketplace?

### ISSUE THREAD

**Issue by dickvalentine** [thSoft/elysium#206]
After updating to Eclipse v 2024-03 on my Macbook running Sonoma 14.4.1, Elysium appears completely gone from my environment. I tried to re-install, but Elysium is not found in Marketplace, nor does the "install" button on the http://elysium.thsoft.hu/ website work. Is there a way I can work around these issues to get Elysium working in my environment again? thanks.

**Comment by thSoft** [comment]
Sorry for the inconvenience, it looks like Elysium was removed from the Eclipse Marketplace without notice. While I'm restoring the entry, please use the following workaround to install Elysium:
* Choose *Help > Install New Software...*
* In *Work with:*, enter `https://bitbucket.org/thsoft/thsoft-update/raw/master/`
* Select *Elysium* and install it

**Comment by dickvalentine** [comment]
thank you!
