### ISSUE TITLE
Create Oomph setup

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#60]
```
Automate Developer's Guide by creating an Oomph setup for the project.
```

Original issue reported on code.google.com by `harmathdenes` on 21 Nov 2014 at 1:25

**Comment by thSoft** [comment]
@nittka: I enhanced the setup after migrating to GitHub. Could you please test it?

**Comment by nittka** [comment]
I just tried in on my Mac. Generally, it seems to work. The Variable Task asking for the LilyPond executable does not have a file selection dialog - I thought it did on my Windows machine. I will check that and may file an Oomph bug...
