### ISSUE TITLE
new git repository location

### ISSUE THREAD

**Issue by GoogleCodeExporter** [thSoft/elysium#64]
```
Is there a plan where the project will be hosted when google code goes offline? 
I vote for GitHub, so that I won't have to create a new account ;-)
```

Original issue reported on code.google.com by `nit...@itemis.de` on 20 Mar 2015 at 11:25

**Comment by thSoft** [comment]
I migrated https://github.com/thSoft/elysium and https://github.com/thSoft/eclipse-commons. I'm going to close this issue when I have updated the Oomph setup.
