### ISSUE TITLE
Handle non-toplevel includes

### ISSUE THREAD

**Issue by thSoft** [thSoft/elysium#79]
Currently, the grammar takes only top-level includes into account. According to http://www.lilypond.org/doc/v2.19/Documentation/notation/file-structure, \include is valid at any point in a file. E.g. titling-init.ly is included in paper-defaults-init.ly in a \paper block, which isn't handled by the current grammar.

**Comment by nittka** [comment]
The error description is not quite correct. When looking for includes, nested elements are indeed taken into account, however the current grammar causes the \include to be contained in an unparsed block, so it is not recognized as include, but rather as unparsed command.

**Comment by nittka** [comment]
Should be fixed with #83 (regression test is added). If there are further places where an include is possible (within Scheme?), these should be dealt with in a new ticket.
