### ISSUE TITLE
Handle scheme module imports

### ISSUE THREAD

**Issue by thSoft** [thSoft/elysium#93]
Support `use-modules` Scheme command. E.g. `snippets/accordion-registers.ly` calls `#(use-modules (scm accreg))` to include [accreg.scm](http://git.savannah.gnu.org/gitweb/?p=lilypond.git;a=blob;f=scm/accreg.scm;h=6aea74c6613f1b55134d5d09dbc8006960d5e369;hb=HEAD), but `\discant`, `\stdBass` etc. can't be resolved.

**Comment by nittka** [comment]
Without implementing the entire language, this issue can be addressed (workaround) by adding such definitions from the default imports to the list of ignored linking errors (see #99). I added the three definitions from the above example to the preference default values.

**Comment by nittka** [comment]
I consider this ticket resolved. Supporting scheme syntax in general is a separate matter and should be tracked in a different issue.
