### ISSUE TITLE
Exclude .ily files from compilation

### ISSUE THREAD

**Issue by nittka** [thSoft/elysium#95]
Should .ily files be excluded from the compile process? Changes there should trigger compilation of the including files, but the ily file itself need not be passed to the compiler.

I noticed in real world examples I found on GitHub that the ily-files by themselves could cause LilyPond compile errors while the main file including them is OK. This exclusion would also improve performance due to fewer compiler calls.

**Comment by thSoft** [comment]
You are right, they should not be directly passed to the LilyPond compiler, but only to the Xtext builder. As you noticed, this will make more real-world integration tests pass.

**Comment by thSoft** [comment]
Fixed in 56b164c
